---
title: Childes words for Wordful App
date: "`r Sys.Date()`"
output:
  html_document:
    highlight: tango
    toc: true
    number_sections: false
    theme: cerulean
    toc_float: true
    code_folding: hide
---

```{r setup, message=FALSE, warning = F}
library(knitr)

opts_chunk$set(echo = T, message = F, warning = F, 
               error = F, cache = F, tidy = F)

library(tidyverse)
library(childesr)
library(feather)
library(langcog)
library(broom)

theme_set(theme_classic(base_size = 10))

```

Send me the top ~300 words from CHILDES that that 2.5+ year olds produced (for seeding Wordful, the app we’re developing). Let’s limit it to words that between 20% and 80% kids said, i.e., omit words that more than 80% of kids said

Get American English CHILDES data
```{r}
all_tokens <- get_tokens(collection = "Eng-NA", role = "Target_Child", token = "*")
```

I'm looking at types only (included if kid said word at least once).
```{r}
two_half <- 2*365 + (365/2)

tokens_twos <- all_tokens %>% 
  filter(target_child_age >= two_half)  %>%
  select(speaker_id, gloss) %>%
  group_by(speaker_id, gloss) %>%
  slice(1) %>%
  ungroup()

num_kids <- length(unique(tokens_twos$speaker_id))

total_counts <- tokens_twos %>%
  count(gloss) %>%
  mutate(prop_know = n/num_kids)

target_prop <- total_counts %>%
  #filter(prop_know > .2 & prop_know < .8) %>%
  arrange(-prop_know) %>%
  select(-n)  # there are 520

NUM_WORDS <- 300
target_prop_sampled <- sample_n(target_prop, NUM_WORDS)  


#write_csv(target_prop, "all_top_words_for_2.5yo.csv")
#write_csv(target_prop_sampled, "all_top_words_for_2.5yo_sampled.csv")
```