---
title: Childes Exploration with tf_idf
date: "`r Sys.Date()`"
output:
  html_document:
    highlight: tango
    toc: true
    number_sections: false
    theme: cerulean
    toc_float: true
    code_folding: hide
---

```{r setup, message=FALSE, warning = F}
library(knitr)

opts_chunk$set(echo = T, message = F, warning = F, 
               error = F, cache = F, tidy = F)

library(tidyverse)
library(childesr)
library(feather)
library(langcog)
library(modelr)
library(broom)
library(lme4)

theme_set(theme_classic(base_size = 10))

```

### Get American English CHILDES data
```{r}
d_eng_na <- get_transcripts(collection = "Eng-NA", 
                            corpus = NULL, 
                            child = NULL) %>%
  mutate_if(is.character, as.factor) %>%
  filter(language == "eng") %>%
  filter(!is.na(target_child_id))

eng_na_children <- d_eng_na  %>%
  filter(target_child_age >= 558, 
         target_child_age <= 1350) %>%
  distinct(target_child_id, .keep_all = T) %>%
  select(target_child_id, corpus_name, target_child_name) 
```


```{r}
utts <- get_utterances(corpus = "Clark", 
                              role = "Target_Child",
                              child = "Shem") %>%
  select(corpus_id, target_child_name, id, transcript_id, gloss)
```

```{r}
write_utts <- function(target_child_id,
                       corpus_name,
                       target_child_name){
  
  print(target_child_id)
  print(corpus_name)
  print(target_child_name)
  
  utts <- get_utterances(corpus = corpus_name, 
                              role = c("Mother", "Father", "Adult"), #Target_Child
                              child = target_child_name) %>%
          select(corpus_id, target_child_name, 
                     id, transcript_id, gloss)


  
  file_name <- paste0("childes_utt_data/child_id_", 
                      target_child_id, "_parent_utts.feather") 
  write_feather(utts, file_name)
}
eng_na_children %>%
  mutate_all(as.character) %>%
  as.list() %>%
  pwalk(write_utts)
```

```{r}

all_parrent_utts <- map_df(eng_na_children$target_child_id, function(x){  
  file_name <- paste0("childes_utt_data/child_id_",
                      x, "_parent_utts.feather") 
  read_feather(file_name)
}) 

```
